### ISSUE TITLE
Suggestion: Use Pipenv to manage dependencies and virtualenvs

### ISSUE THREAD

**Issue by gfrewqpoiu** [HyperGH/annomatchmakingbot#14]
I personally use [Pipenv](https://pipenv.pypa.io/en/latest/) whenever I make any Python project since it makes dependency management really easy, and it also handles stuff like Python Virtual Environments for you. Getting the bot ready for use would then just be `pipenv install --deploy` and it would install everything needed for the bot to run. So, I would suggest using it for this project.
If you want to, I can make a Pull Request with the necessary changes.

**Comment by HyperGH** [comment]
I will look into this! :)

**Comment by HyperGH** [comment]
I don't quite get why this would be needed since we have a grand total of 2 dependencies, but if you want to make this, I won't complain. 😛

**Comment by HyperGH** [comment]
Merged in #17
