### ISSUE TITLE
Transition the settings to SQLite

### ISSUE THREAD

**Issue by HyperGH** [HyperGH/annomatchmakingbot#6]
Now I just need to figure out how databases work...

**Comment by HyperGH** [comment]
Now on the experimental branch

**Comment by gfrewqpoiu** [comment]
For the settings, I would suggest using either JSON or just using [Configparser](https://docs.python.org/3/library/configparser.html) from the standard library unless you need to persist some state across bot restarts.
For that, something like Peewee would probably be your best bet.
I am rn trying out EdgeDB personally, but it is still in early beta and probably too complex for this use case.

**Comment by gfrewqpoiu** [comment]
And if it is just for bot internal storage (like saving which channel is the commands channel etc.) that the end-user should not touch because it is handled by commands anyway, [shelve](https://docs.python.org/3/library/shelve.html#module-shelve) might be an option.

**Comment by HyperGH** [comment]
Too late, SQLite is already fully implemented :) Since I need to store data per guild and also make it user-modifiable to an extent, I settled on this light-weight local SQL implementation.

**Comment by HyperGH** [comment]
I considered json's, but SQL is better structured for what I am storing/retrieving.

**Comment by gfrewqpoiu** [comment]
Yeah. But for that kind of scale you would need to use Postgres etc.
But yeah SQL is the obvious choice. I only saw the experimental branch once I forked the repo.

**Comment by HyperGH** [comment]
Weird.
